chore: add constraints file
googleapis/python-dialogflow pull request #236
Opened 2020-12-04 00:48 UTC by busunkim96

Add constraints file to test lower bounds

2021-03-09 19:44 UTC, parthea requested changes

2021-03-09 19:44 UTC, parthea commented on testing/constraints-3.6.txt
> +google-api-core==1.22.0
Also [proto-plus](https://github.com/googleapis/python-dialogflow/blob/master/setup.py#L24) 
```suggestion
google-api-core==1.22.0
proto-plus==1.10.0
```

2021-03-30 09:40 UTC, parthea commented
@busunkim96 Just one observation

2021-03-30 14:58 UTC, busunkim96 commented on testing/constraints-3.6.txt
> +google-api-core==1.22.0
Thanks!

2021-03-30 18:51 UTC, parthea commented
One of the checks is failing : `Samples - Python 3.7`

2021-03-30 19:39 UTC, busunkim96 commented
Looks like it's from quota issues.

```
value = None
from_value = <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "Quota exceeded for...ns per minute' of service 'dialogflow.googleapis.com' for consumer 'project_number:1012616486416'.","grpc_status":8}"
>

>   ???
E   google.api_core.exceptions.ResourceExhausted: 429 Quota exceeded for quota metric 'Dialogflow Trial Edition text query operations' and limit 'Dialogflow Trial Edition text query operations per minute' of service 'dialogflow.googleapis.com' for consumer 'project_number:1012616486416'.

```

I re-triggered the 3.7 build.

2021-03-30 19:55 UTC, busunkim96 commented
@parthea PTAL

2021-03-30 20:12 UTC, parthea approved these changes

2021-03-30 20:14 UTC, merged